/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import '@ionic/core';
import 'ionicons';

import {
  AuthService,
} from './services/auth';
import {
  ConfigService,
} from './services/config';

declare global {

  namespace StencilComponents {
    interface AppHome {
      'auth': AuthService;
      'config': ConfigService;
    }
  }

  interface HTMLAppHomeElement extends StencilComponents.AppHome, HTMLStencilElement {}

  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-home': JSXElements.AppHomeAttributes;
    }
  }
  namespace JSXElements {
    export interface AppHomeAttributes extends HTMLAttributes {
      'auth'?: AuthService;
      'config'?: ConfigService;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface MadnessLabsPwa {

    }
  }

  interface HTMLMadnessLabsPwaElement extends StencilComponents.MadnessLabsPwa, HTMLStencilElement {}

  var HTMLMadnessLabsPwaElement: {
    prototype: HTMLMadnessLabsPwaElement;
    new (): HTMLMadnessLabsPwaElement;
  };
  interface HTMLElementTagNameMap {
    'madness-labs-pwa': HTMLMadnessLabsPwaElement;
  }
  interface ElementTagNameMap {
    'madness-labs-pwa': HTMLMadnessLabsPwaElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'madness-labs-pwa': JSXElements.MadnessLabsPwaAttributes;
    }
  }
  namespace JSXElements {
    export interface MadnessLabsPwaAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
